name: Go package
on:
    push:
        branches:
            - main
    pull_request:
        branches:
        - main
        - dev
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  # golangci:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code into the Go module directory
  #       uses: actions/checkout@v3
  #     - name: golangci-lint
  #       uses: reviewdog/action-golangci-lint@v2
  #       with:
  #         # optionally use a specific version of Go rather than the latest one
  #         go_version: "1.19"
  #         filter_mode: nofilter
  #         # Can pass --config flag to change golangci-lint behavior and target
  #         # directory.
  #         golangci_lint_flags: >
  #           --config=../.golangci.yml 
  #           --timeout=5m
  #         fail_on_error: true
  #         cache: true
  #         reporter: github-check
